import { readFileSync } from "node:fs";
import { expect, it } from "vitest";
import type {
  Note,
  Observation,
  Snapshot,
  Source,
  Summary,
  Tag,
} from "../domain/types";

type Check = (value: unknown) => void;
type Shape<T> = { [K in keyof T]-?: Check };
const string: Check = (value) => expect(typeof value).toBe("string");
const number: Check = (value) => expect(typeof value).toBe("number");
const nullable =
  (check: Check): Check =>
  (value) => {
    if (value !== null) check(value);
  };
const array =
  (check: Check): Check =>
  (value) => {
    expect(Array.isArray(value)).toBe(true);
    (value as unknown[]).forEach(check);
  };
const object =
  <T>(shape: Shape<T>): Check =>
  (value) => {
    expect(value).toBeTypeOf("object");
    expect(value).not.toBeNull();
    const record = value as Record<string, unknown>;
    expect(Object.keys(record).sort()).toEqual(Object.keys(shape).sort());
    for (const [key, check] of Object.entries(shape))
      (check as Check)(record[key]);
  };
const observation = object<Observation>({
  availability: (value) =>
    expect(["present", "missing", "unavailable"]).toContain(value),
  size_bytes: nullable(number),
  file_modified_at: nullable(string),
  content_hash: nullable(string),
});
const source = object<Source>({
  id: string,
  path: string,
  title: string,
  description: string,
  source_url: string,
  tag_ids: array(string),
  created_at: string,
  modified_at: string,
  observation,
});
const note = object<Note>({
  id: string,
  source_id: string,
  title: string,
  description: string,
  created_at: string,
  modified_at: string,
});
const tag = object<Tag>({
  id: string,
  name: string,
  description: string,
  created_at: string,
  modified_at: string,
});
const snapshot = object<Snapshot>({
  root: string,
  note_sizes: (value) => {
    expect(value).toBeTypeOf("object");
    Object.values(value as object).forEach(nullable(number));
  },
  catalog: object<Snapshot["catalog"]>({
    sources: array(source),
    notes: array(note),
    tags: array(tag),
  }),
});

it("checks the IPC shape serialized by the actual Rust model", () => {
  // Generated by pretest; a stale hand-written fixture cannot satisfy the build gate.
  const fixture = JSON.parse(
    readFileSync("target/frontend-contract.json", "utf8"),
  );
  snapshot(fixture.snapshot);
  expect(fixture.snapshot.catalog.sources.length).toBeGreaterThan(0);
  expect(fixture.snapshot.catalog.notes.length).toBeGreaterThan(0);
  expect(fixture.snapshot.catalog.tags.length).toBeGreaterThan(0);
  expect(fixture.availabilities).toEqual(["present", "missing", "unavailable"]);
  object<Summary>({
    scanned: number,
    added: number,
    moved: number,
    missing: number,
    unavailable: number,
    warnings: array(string),
  })(fixture.summary);
});
